name: Unit tests

on:
  push:
    branches:
      - master
      - dev*
  pull_request:
    branches:
      - master
      - dev*

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest]
        haxe: [4.3.3]
      fail-fast: true
    runs-on: windows-latest

    steps:
      # Checkout & install haxe
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version

      # Install libs
      - run: haxelib install tests/js.hxml --always
      - run: haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git
      - run: haxelib git heaps https://github.com/deepnight/heaps.git
      - run: haxelib git hlsdl https://github.com/HaxeFoundation/hashlink.git master libs/sdl
      - run: haxelib list

      # Run tests
      - name: JS tests
        run: haxe tests/js.hxml

      # Samples
      - name: Samples building
        working-directory: ./samples/_initSamples
        run: haxe initSamples.hxml
